# Generated by Django 5.2.17 on 2026-09-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyconfig',
            name='public_ip',
        ),
    ]
