# Generated by Django 5.2.17 on 2026-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_remove_proxyconfig_public_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyconfig',
            old_name='protocol',
            new_name='backend_protocol',
        ),
        migrations.AddField(
            model_name='proxyconfig',
            name='incoming_protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=5),
        ),
    ]
