# Generated by Django 5.2.17 on 2026-09-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0004_add_public_ip_and_certificate_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('latest', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
