# Generated by Django 5.2.17 on 2026-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0005_servermonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermonitor',
            name='is_reverse_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
