# Generated by Django 5.2.17 on 2026-09-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0007_accountprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100, unique=True)),
                ('offset', models.PositiveBigIntegerField(default=0)),
                ('anchor', models.BinaryField(default=bytes)),
                ('skipping', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['domain', '-id'], name='traffic_domain_id')],
            },
        ),
    ]
