# Generated by Django 5.2.17 on 2026-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0008_trafficcursor_trafficevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='websocket_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable WebSocket support'),
        ),
    ]
