# Generated by Django 5.2.17 on 2026-10-01 15:09

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0012_traffic_domain_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptiveRateLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='proxyconfig',
            name='captive_portal_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable OTP captive portal'),
        ),
        migrations.CreateModel(
            name='CaptivePortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=120)),
                ('rank', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('all_fqdns', models.BooleanField(default=False, verbose_name='Allow access to all captive-enabled FQDNs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_successful_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captive_users_created', to=settings.AUTH_USER_MODEL)),
                ('proxies', models.ManyToManyField(blank=True, related_name='captive_users', to='proxies.proxyconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captive_users_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'permissions': [('toggle_captiveportaluser', 'Enable or disable authorized users'), ('assign_captiveportaluser', 'Assign authorized user FQDN access')],
            },
        ),
        migrations.CreateModel(
            name='CaptiveOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_hash', models.CharField(max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=5)),
                ('destination_fingerprint', models.CharField(max_length=64)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField(null=True)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxies.proxyconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captive_otps', to='proxies.captiveportaluser')),
            ],
        ),
        migrations.CreateModel(
            name='CaptiveAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('channel', models.CharField(blank=True, max_length=5)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxies.proxyconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxies.captiveportaluser')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CaptiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxies.proxyconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captive_sessions', to='proxies.captiveportaluser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='captiveportaluser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email_address'), name='captive_unique_email'),
        ),
        migrations.AddConstraint(
            model_name='captiveportaluser',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('mobile_number__isnull', False), ('email_address__isnull', False), _connector='OR'), name='captive_contact_required'),
        ),
    ]
