# Generated by Django 5.2.17 on 2026-10-03 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0015_captiveotp_client_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='captiveportaluser',
            name='captive_contact_required',
        ),
        migrations.AlterField(
            model_name='captiveportaluser',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='captiveportaluser',
            name='rank',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='captiveportaluser',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('is_enabled', False), models.Q(('mobile_number__isnull', False), models.Q(('mobile_number', ''), _negated=True)), _connector='OR'), name='captive_contact_required'),
        ),
    ]
